"""The restatement run registry: legacy identifiers resolved to canonical ones, additively.

WHY A REGISTRY INSTEAD OF A CORRECTION. The 5,925,913 published rows of pub:v2 carry
`restate:6b3923771883e860`, an identifier produced by a scheme that could not tell two cohorts
apart. The tempting fix -- UPDATE the published rows to carry the canonical id -- would destroy the
one property Phase 6 exists to demonstrate: that a published figure is immutable and is corrected by
a new statement rather than by an edit. A restatement of a restatement's identity is still a
restatement.

So the correction is a NEW table that maps one to the other, and it carries both the identity and
the reason the old one was insufficient. The published rows are not touched.

WHAT THE REGISTRY PROVES BY BEING QUERYABLE:

    * the run that produced pub:v2 has a canonical identity that includes its cohort;
    * the cohort that was REJECTED before publication has a DIFFERENT canonical identity;
    * both of those map back to the SAME legacy string, which is the collision, recorded rather
      than quietly erased.

The rows are generated from src/restatement/identity.py and config/restatement_cohorts.yml, and the
dbt model is generated from these rows, so the warehouse cannot drift from the identity module. A
unit test fails if the checked-in SQL stops matching the generator.
"""

from __future__ import annotations

import argparse
import json
import pathlib

from restatement.identity import (
    IDENTITY_SCHEME,
    LEGACY_INPUTS,
    LEGACY_RUN_ID,
    CohortDefinition,
    RestatementInputs,
    inputs_for_published_restatement,
    legacy_run_id,
    load_cohorts,
)

MODEL_PATH = (pathlib.Path(__file__).parents[2]
              / "dbt/models/finance/restatement_run_registry.sql")

#: Which publication each run produced. A rejected cohort produced none, and saying so is the
#: point: the registry has to be able to describe a run that was built and thrown away.
PUBLICATION_OF_RUN = {
    "partial-empty-hangul-kana": "pub:v2",
    "script-only-no-failure-reason-restriction": "",
}


def registry_rows(cohorts: dict[str, CohortDefinition] | None = None) -> list[dict]:
    """One row per known restatement run identity. Pure: no warehouse, no clock."""
    registry = cohorts if cohorts is not None else load_cohorts()
    legacy = legacy_run_id(**LEGACY_INPUTS)
    rows = []
    for key, cohort in registry.items():
        inputs: RestatementInputs = inputs_for_published_restatement(registry, key)
        rows.append({
            "canonical_run_id": inputs.run_id,
            "identity_scheme": IDENTITY_SCHEME,
            "inputs_digest": inputs.inputs_digest,
            "legacy_run_id": legacy,
            "legacy_scheme": LEGACY_RUN_ID.scheme,
            # TRUE on every row, and that is the finding: one legacy string, two runs.
            "legacy_id_is_ambiguous": True,
            "cohort_key": cohort.cohort_key,
            "cohort_sha256": cohort.digest,
            "cohort_status": cohort.status,
            "new_publication_id": PUBLICATION_OF_RUN.get(key, ""),
            "published_rows_carry_legacy_id": (
                LEGACY_RUN_ID.published_rows_carry_it and bool(PUBLICATION_OF_RUN.get(key))),
            "measured_listens": cohort.measured_listens,
            "measured_distinct_pairs": cohort.measured_distinct_pairs,
            "canonical_inputs": inputs.canonical_payload(),
            "cohort_predicate": cohort.canonical_predicate(),
            "why_legacy_insufficient": LEGACY_RUN_ID.why_insufficient,
            "legacy_missing_inputs": list(LEGACY_RUN_ID.missing_inputs),
            "cohort_notes": " ".join(cohort.notes.split()),
        })
    return sorted(rows, key=lambda r: r["canonical_run_id"])


def _sql_string(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, (dict, list)):
        value = json.dumps(value, sort_keys=True, separators=(",", ":"))
    return "'" + str(value).replace("\\", "\\\\").replace("'", "\\'") + "'"


def registry_model_sql(cohorts: dict[str, CohortDefinition] | None = None) -> str:
    """Render the dbt model. GENERATED -- edit identity.py or the cohort config, then regenerate."""
    rows = registry_rows(cohorts)
    header = "\n".join([
        "{{ config(materialized = 'table') }}",
        "",
        "-- GENERATED by src/restatement/registry.py. Do not edit by hand:",
        "-- tests/unit/test_restatement_identity.py fails if this file stops matching the",
        "-- generator, so a cohort or identity change cannot leave the warehouse behind.",
        "--",
        "-- THE RESTATEMENT RUN REGISTRY. Legacy identifiers resolved to canonical ones, additively.",
        "--",
        f"-- The published rows of pub:v2 carry `{LEGACY_RUN_ID.run_id}`, produced by a scheme that",
        "-- hashed the versions alone: the cohort was not part of the hash, so the rejected",
        "-- 1,377,862-listen cohort and the published 982,322-listen cohort produced the SAME",
        "-- identifier under the same versions.",
        "--",
        "-- They are NOT rewritten. A published figure is corrected by a new statement, never by an",
        "-- edit, and that applies to its identity as much as to its amount. Both rows below carry",
        "-- the same legacy_run_id and different canonical_run_ids: the collision recorded as data.",
        "--",
        f"-- canonical_run_id = restate:{IDENTITY_SCHEME}:<first 16 hex of sha256(canonical inputs)>,",
        "-- whose inputs include the cohort digest -- the term the legacy scheme was missing.",
        "",
        "",
    ])
    columns = list(rows[0].keys())
    selects = []
    for row in rows:
        cols = ",\n".join(f"        {_sql_string(row[c])} as {c}" for c in columns)
        selects.append(f"    select\n{cols}")
    body = "with runs as (\n" + "\n\n    union all\n\n".join(selects) + "\n)\n\n"
    body += "select\n    " + ",\n    ".join(columns) + ",\n    current_timestamp() as measured_at\n"
    body += "from runs\norder by canonical_run_id\n"
    return header + body


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true", help="regenerate the dbt model")
    args = ap.parse_args()
    sql = registry_model_sql()
    if args.write:
        MODEL_PATH.write_text(sql)
        print(f"wrote {MODEL_PATH.relative_to(pathlib.Path(__file__).parents[2])}")
    for row in registry_rows():
        print(f"  {row['canonical_run_id']}  <- {row['legacy_run_id']}  "
              f"{row['cohort_key']:<44} {row['cohort_status']:<28} "
              f"{row['measured_listens']:>10,} listens  pub={row['new_publication_id'] or '-'}")


if __name__ == "__main__":
    main()
