{{ config(materialized = 'table') }}

-- GENERATED by src/restatement/registry.py. Do not edit by hand:
-- tests/unit/test_restatement_identity.py fails if this file stops matching the
-- generator, so a cohort or identity change cannot leave the warehouse behind.
--
-- THE RESTATEMENT RUN REGISTRY. Legacy identifiers resolved to canonical ones, additively.
--
-- The published rows of pub:v2 carry `restate:6b3923771883e860`, produced by a scheme that
-- hashed the versions alone: the cohort was not part of the hash, so the rejected
-- 1,377,862-listen cohort and the published 982,322-listen cohort produced the SAME
-- identifier under the same versions.
--
-- They are NOT rewritten. A published figure is corrected by a new statement, never by an
-- edit, and that applies to its identity as much as to its amount. Both rows below carry
-- the same legacy_run_id and different canonical_run_ids: the collision recorded as data.
--
-- canonical_run_id = restate:v1:<first 16 hex of sha256(canonical inputs)>,
-- whose inputs include the cohort digest -- the term the legacy scheme was missing.

with runs as (
    select
        'restate:v1:2f08f786d0d3e552' as canonical_run_id,
        'v1' as identity_scheme,
        '2f08f786d0d3e55244e2278557c7a713a855b33a83271c041a8bb608abb5fc44' as inputs_digest,
        'restate:6b3923771883e860' as legacy_run_id,
        'legacy-unversioned' as legacy_scheme,
        true as legacy_id_is_ambiguous,
        'partial-empty-hangul-kana' as cohort_key,
        'cc9e4a61308b6f31a77fe31576fd4e81e3f380e0e6bab6609d30c8b3925705d5' as cohort_sha256,
        'PUBLISHED' as cohort_status,
        'pub:v2' as new_publication_id,
        true as published_rows_carry_legacy_id,
        982322 as measured_listens,
        147599 as measured_distinct_pairs,
        '{"canonical_snapshot_date":"2026-07-17","cohort_digest":"cc9e4a61308b6f31a77fe31576fd4e81e3f380e0e6bab6609d30c8b3925705d5","identity_scheme":"v1","new_normalization_version":"1.1.0+b3253b155934","payout_policy_version":"1.0.0+84b4b68a37c9","period_end":"2026-07-01","period_start":"2026-06-01","prior_normalization_version":"1.0.0+0bc0dd643e06","prior_publication_id":"pub:v1","rights_version":"1.0.0+47f801102e17","rule_version_id":"rc-1.0.0","scoring_version":"1.0.0+cb21f9704ff0","trigger_reason":"TRANSLITERATION_KOREAN_JAPANESE_TITLES"}' as canonical_inputs,
        '{"period_end":"2026-07-01","period_start":"2026-06-01","prior_failure_reasons":["NO_LOOKUP_KEY_EMPTY","NO_LOOKUP_KEY_PARTIAL"],"required_scripts_any":["hangul","kana"],"string_fields_examined":["artist_name","recording_name"]}' as cohort_predicate,
        'the cohort was not part of the hash, so the rejected 1,377,862-listen cohort and the published 982,322-listen cohort produced the SAME identifier under the same versions' as why_legacy_insufficient,
        '["period","prior_publication_id","prior_normalization_version","payout_policy_version","rights_version","rule_version_id","trigger_reason","canonical_snapshot_date","cohort_definition"]' as legacy_missing_inputs,
        'exactly the definition frozen in config/restatement_trigger.yml. Every listen in scope was unmatched under pub:v1, so no v1 match can be lost.' as cohort_notes

    union all

    select
        'restate:v1:67646757af1bf447' as canonical_run_id,
        'v1' as identity_scheme,
        '67646757af1bf447e4002a8504a57bf4467b8b29d47bd42728350f0297c61460' as inputs_digest,
        'restate:6b3923771883e860' as legacy_run_id,
        'legacy-unversioned' as legacy_scheme,
        true as legacy_id_is_ambiguous,
        'script-only-no-failure-reason-restriction' as cohort_key,
        '90eaec5b2be2c3dfa7a07de0a7541396a721da4d166cd17534adf02ee86794e3' as cohort_sha256,
        'REJECTED_BEFORE_PUBLICATION' as cohort_status,
        '' as new_publication_id,
        false as published_rows_carry_legacy_id,
        1377862 as measured_listens,
        204902 as measured_distinct_pairs,
        '{"canonical_snapshot_date":"2026-07-17","cohort_digest":"90eaec5b2be2c3dfa7a07de0a7541396a721da4d166cd17534adf02ee86794e3","identity_scheme":"v1","new_normalization_version":"1.1.0+b3253b155934","payout_policy_version":"1.0.0+84b4b68a37c9","period_end":"2026-07-01","period_start":"2026-06-01","prior_normalization_version":"1.0.0+0bc0dd643e06","prior_publication_id":"pub:v1","rights_version":"1.0.0+47f801102e17","rule_version_id":"rc-1.0.0","scoring_version":"1.0.0+cb21f9704ff0","trigger_reason":"TRANSLITERATION_KOREAN_JAPANESE_TITLES"}' as canonical_inputs,
        '{"period_end":"2026-07-01","period_start":"2026-06-01","prior_failure_reasons":[],"required_scripts_any":["hangul","kana"],"string_fields_examined":["artist_name","recording_name"]}' as cohort_predicate,
        'the cohort was not part of the hash, so the rejected 1,377,862-listen cohort and the published 982,322-listen cohort produced the SAME identifier under the same versions' as why_legacy_insufficient,
        '["period","prior_publication_id","prior_normalization_version","payout_policy_version","rights_version","rule_version_id","trigger_reason","canonical_snapshot_date","cohort_definition"]' as legacy_missing_inputs,
        'dropped the failure-reason half of the frozen predicate, pulling in 395,540 listens that already had a lookup key and costing 29,954 previously matched ones, because transliteration CHANGES existing keys for mixed Latin/CJK strings as well as adding new ones. Never published.' as cohort_notes
)

select
    canonical_run_id,
    identity_scheme,
    inputs_digest,
    legacy_run_id,
    legacy_scheme,
    legacy_id_is_ambiguous,
    cohort_key,
    cohort_sha256,
    cohort_status,
    new_publication_id,
    published_rows_carry_legacy_id,
    measured_listens,
    measured_distinct_pairs,
    canonical_inputs,
    cohort_predicate,
    why_legacy_insufficient,
    legacy_missing_inputs,
    cohort_notes,
    current_timestamp() as measured_at
from runs
order by canonical_run_id
